name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-14, ubuntu-latest]
        java: ['21']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'liberica'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
    - name: Install MSYS2 on Windows
      if: startsWith(matrix.os, 'windows')
      uses: msys2/setup-msys2@v2
      with:
        update: true
        pacboy: lcms2:m libraw:m lensfun:m ntldd-git:m pkgconf:m
    - name: Build on Windows
      if: startsWith(matrix.os, 'windows')
      shell: bash
      run: |
        export PATH=/msys64/usr/bin/:/msys32/usr/bin/:$PATH
        export MSSDK_HOME=/c/Program\ Files\ \(x86\)/Windows\ Kits/10/Lib/10.0.22621.0
        ./gradlew jpackage -x test
        # MSYSTEM=MINGW32 TARGET_ARCH=i686 ./gradlew jpackage -x test
    - name: Build on macOS
      if: startsWith(matrix.os, 'macos')
      run: |
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
        brew install lensfun libomp libraw
        if [ "${{ matrix.os }}" == "macos-14" ]; then
          export LIBOMP_PATH=/opt/homebrew/opt/libomp
          TARGET_ARCH=arm64 ./gradlew jpackage -x test
        else
          ./gradlew jpackage -x test
        fi
    - name: Build on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo add-apt-repository -y ppa:lightzone-team/lightzone
        sudo apt update -y
        sudo apt install -y \
          libejml-java \
          libglib2.0-dev \
          libjetbrains-annotations-java \
          libjiconfont-font-awesome-java \
          libjiconfont-google-material-design-icons-java \
          libjiconfont-swing-java \
          liblensfun-dev \
          liblombok-java \
          libraw-dev \
          libtiff-dev \
          tidy
        ./gradlew build -x test
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LightZone-${{ matrix.os }}
        path: |
          windows/build/jpackage/LightZone-Installer*.exe
          macosx/build/jpackage/LightZone-Installer*.dmg
